# Database
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.initialization-mode=always
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.sqlScriptEncoding=UTF-8
spring.jpa.properties.hibernate.jdbc.time_zone = UTC
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

spring.liquibase.change-log=classpath:liquibase/db.changelog-master.xml
spring.liquibase.enabled=true

# SERVER
server.port=${PORT}
spring.main.allow-bean-definition-overriding=true
#spring.jackson.serialization.INDENT_OUTPUT= true
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

#EXCEPTION HANDLER
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

#LOG
# logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.level.root=WARN
logging.level.com.nails.auth=DEBUG
logging.level.org.springframework.web=WARN
logging.file.path=logs/
logging.file.name=logs/ww-auth.log
logging.file=${catalina.home}/logs/spam.log

#EMAIL
spring.mail.default-encoding=UTF-8
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Feign client
feign.client.config.default.connectTimeout=60000
feign.client.config.default.readTimeout=60000

#APP CONFIG
auth.signing.key=${AUTH_SIGNING_KEY}
auth.expires-in=15m

# Async Config
thread.pool.size=10
thread.pool.queue.size=150

# Media Service
media.internal.base.url=http://localhost:7474

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.media.queue=MOVIE_QUEUE_MEDIA
rabbitmq.sns.broadcast.queue=SNS_BROADCAST_QUEUE
rabbitmq.app=BACKEND_APP

# Redis
redis.sentinel.hosts=${REDIS_SENTINEL_HOSTS}
redis.master.name=${REDIS_MASTER_NAME}
redis.host=${REDIS_HOST}
redis.type=${REDIS_TYPE}
redis.password=${REDIS_PASSWORD}
spring.data.redis.repositories.enabled=false

# Google config
social.google.web.client-id=${GOOGLE_WEB_CLIENT_ID}
social.google.web.client-secret=${GOOGLE_WEB_CLIENT_SECRET}
social.google.web.redirect-uri=${GOOGLE_WEB_REDIRECT_URI}
social.google.ios.client-id=${GOOGLE_IOS_CLIENT_ID}
social.google.android.client-id=${GOOGLE_ANDROID_CLIENT_ID}

social.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
social.google.token-uri=https://oauth2.googleapis.com/token
